<?php

namespace Jfelder\OracleDB\Tests;

use Illuminate\Database\Query\Expression as Raw;
use Illuminate\Database\Schema\ForeignIdColumnDefinition;
use Jfelder\OracleDB\OracleConnection;
use Jfelder\OracleDB\Schema\Grammars\OracleGrammar;
use Jfelder\OracleDB\Schema\OracleBlueprint;
use Jfelder\OracleDB\Schema\OracleBuilder;
use LogicException;
use Mockery as m;
use PHPUnit\Framework\TestCase;

include 'mocks/PDOMocks.php';

class OracleDBSchemaGrammarTest extends TestCase
{
    protected function tearDown(): void
    {
        m::close();
    }

    public function test_create_database()
    {
        $grammar = new OracleGrammar($this->getConnection());

        $this->expectException(LogicException::class);
        $this->expectExceptionMessage('This database driver does not support creating databases.');

        $grammar->compileCreateDatabase('foo');
    }

    public function test_drop_database_if_exists()
    {
        $grammar = new OracleGrammar($this->getConnection());

        $this->expectException(LogicException::class);
        $this->expectExceptionMessage('This database driver does not support dropping databases.');

        $grammar->compileDropDatabaseIfExists('foo');
    }

    public function test_compile_table_exists_method()
    {
        $grammar = $this->getGrammar();
        $expected = "select count(*) from all_tables where upper(owner) = upper('schema') and upper(table_name) = upper('test_table')";
        $sql = $grammar->compileTableExists('schema', 'test_table');
        $this->assertEquals($expected, $sql);
    }

    public function test_basic_create_table()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->create();
        $OracleBlueprint->increments('id');
        $OracleBlueprint->string('email');
        $statements = $OracleBlueprint->toSql();

        $this->assertCount(1, $statements);
        $this->assertSame('create table users ( id number(10,0) generated by default on null as identity, email varchar2(255) not null, constraint users_id_primary primary key ( id ))', $statements[0]);
    }

    public function test_basic_create_table_with_primary()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->create();
        $OracleBlueprint->integer('id')->primary();
        $OracleBlueprint->string('email');

        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('create table users ( id number(10,0) not null, email varchar2(255) not null, constraint users_id_primary primary key ( id ))', $statements[0]);
    }

    public function test_basic_create_table_with_prefix()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(prefix: 'prefix_'), 'users');
        $OracleBlueprint->create();
        $OracleBlueprint->increments('id');
        $OracleBlueprint->string('email');

        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('create table prefix_users ( id number(10,0) generated by default on null as identity, email varchar2(255) not null, constraint users_id_primary primary key ( id ))', $statements[0]);
    }

    public function test_basic_create_table_with_default_value_and_is_not_null()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->create();
        $OracleBlueprint->integer('id')->primary();
        $OracleBlueprint->string('email')->default('user@test.com');

        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('create table users ( id number(10,0) not null, email varchar2(255) default \'user@test.com\' not null, constraint users_id_primary primary key ( id ))', $statements[0]);
    }

    public function test_basic_create_table_with_prefix_and_primary()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(prefix: 'prefix_'), 'users');
        $OracleBlueprint->create();
        $OracleBlueprint->integer('id')->primary();
        $OracleBlueprint->string('email');
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('create table prefix_users ( id number(10,0) not null, email varchar2(255) not null, constraint users_id_primary primary key ( id ))', $statements[0]);
    }

    public function test_basic_create_table_with_prefix_primary_and_foreign_keys()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(prefix: 'prefix_'), 'users');
        $OracleBlueprint->create();
        $OracleBlueprint->integer('id')->primary();
        $OracleBlueprint->string('email');
        $OracleBlueprint->integer('foo_id');
        $OracleBlueprint->foreign('foo_id')->references('id')->on('orders');

        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('create table prefix_users ( id number(10,0) not null, email varchar2(255) not null, foo_id number(10,0) not null, constraint users_foo_id_foreign foreign key ( foo_id ) references prefix_orders ( id ), constraint users_id_primary primary key ( id ))', $statements[0]);
    }

    public function test_basic_create_table_with_prefix_primary_and_foreign_keys_with_cascade_delete()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(prefix: 'prefix_'), 'users');
        $OracleBlueprint->create();
        $OracleBlueprint->integer('id')->primary();
        $OracleBlueprint->string('email');
        $OracleBlueprint->integer('foo_id');
        $OracleBlueprint->foreign('foo_id')->references('id')->on('orders')->onDelete('cascade');

        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('create table prefix_users ( id number(10,0) not null, email varchar2(255) not null, foo_id number(10,0) not null, constraint users_foo_id_foreign foreign key ( foo_id ) references prefix_orders ( id ) on delete cascade, constraint users_id_primary primary key ( id ))', $statements[0]);
    }

    public function test_basic_create_table_with_prefix_primary_and_foreign_keys_with_cascade_update()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(prefix: 'prefix_'), 'users');
        $OracleBlueprint->create();
        $OracleBlueprint->integer('id')->primary();
        $OracleBlueprint->string('email');
        $OracleBlueprint->integer('foo_id');
        $OracleBlueprint->foreign('foo_id')->references('id')->on('orders')->onUpdate('cascade');

        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('create table prefix_users ( id number(10,0) not null, email varchar2(255) not null, foo_id number(10,0) not null, constraint users_foo_id_foreign foreign key ( foo_id ) references prefix_orders ( id ) on update cascade, constraint users_id_primary primary key ( id ))', $statements[0]);
    }

    public function test_basic_alter_table()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->increments('id');
        $OracleBlueprint->string('email');

        $statements = $OracleBlueprint->toSql();

        // echo "\n{$statements[0]}\n{$statements[1]}\n{$statements[2]}\n";

        $this->assertCount(2, $statements);
        $this->assertSame([
            'alter table users add ( id number(10,0) generated by default on null as identity, constraint users_id_primary primary key ( id ))',
            'alter table users add ( email varchar2(255) not null )',
        ], $statements);
    }

    public function test_basic_alter_table_with_prefix()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(prefix: 'prefix_'), 'users');
        $OracleBlueprint->increments('id');
        $OracleBlueprint->string('email');

        $statements = $OracleBlueprint->toSql();

        // todo fix OracleGrammar.php code to name the constraint prefix_users_id_primary

        $this->assertCount(2, $statements);
        $this->assertSame([
            'alter table prefix_users add ( id number(10,0) generated by default on null as identity, constraint users_id_primary primary key ( id ))',
            'alter table prefix_users add ( email varchar2(255) not null )',
        ], $statements);
    }

    public function test_drop_table()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->drop();
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('drop table users', $statements[0]);
    }

    public function test_drop_table_with_prefix()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->drop();
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('drop table users', $statements[0]);
    }

    public function test_drop_if_exists_table()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->dropIfExists();
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals("begin execute immediate 'drop table users'; exception when others then if sqlcode != -942 then raise; end if; end;", $statements[0]);
    }

    public function test_drop_column()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->dropColumn('foo');
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('alter table users drop ( foo )', $statements[0]);

        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->dropColumn(['foo', 'bar']);
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('alter table users drop ( foo, bar )', $statements[0]);

        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->dropColumn('foo', 'bar');
        $statements = $OracleBlueprint->toSql();

        $this->assertCount(1, $statements);
        $this->assertSame('alter table users drop ( foo, bar )', $statements[0]);
    }

    public function test_drop_primary()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->dropPrimary('users_pk');
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('alter table users drop constraint users_pk', $statements[0]);
    }

    public function test_drop_unique()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->dropUnique('foo');
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('alter table users drop constraint foo', $statements[0]);
    }

    public function test_drop_index()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->dropIndex('foo');
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('drop index foo', $statements[0]);
    }

    public function test_drop_foreign()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->dropForeign('foo');
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('alter table users drop constraint foo', $statements[0]);
    }

    public function test_drop_timestamps()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->dropTimestamps();
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('alter table users drop ( created_at, updated_at )', $statements[0]);
    }

    public function test_drop_timestamps_tz()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->dropTimestampsTz();
        $statements = $OracleBlueprint->toSql();

        $this->assertCount(1, $statements);
        $this->assertSame('alter table users drop ( created_at, updated_at )', $statements[0]);
    }

    public function test_drop_morphs()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'photos');
        $OracleBlueprint->dropMorphs('imageable');
        $statements = $OracleBlueprint->toSql();

        $this->assertCount(2, $statements);
        $this->assertSame('drop index photos_imageable_type_imageable_id_index', $statements[0]);
        $this->assertSame('alter table photos drop ( imageable_type, imageable_id )', $statements[1]);
    }

    public function test_rename_table()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->rename('foo');
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('alter table users rename to foo', $statements[0]);
    }

    public function test_rename_table_with_prefix()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(prefix: 'prefix_'), 'users');
        $OracleBlueprint->rename('foo');

        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('alter table prefix_users rename to prefix_foo', $statements[0]);
    }

    public function test_adding_primary_key()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->primary('foo', 'bar');
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('alter table users add constraint bar primary key (foo)', $statements[0]);
    }

    public function test_adding_unique_key()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->unique('foo', 'bar');
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('alter table users add constraint bar unique ( foo )', $statements[0]);
    }

    public function test_adding_index()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->index(['foo', 'bar'], 'baz');
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));

        $this->assertEquals('create index baz on users ( foo, bar )', $statements[0]);
    }

    public function test_adding_raw_index()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->rawIndex('(function(column))', 'raw_index');
        $statements = $OracleBlueprint->toSql();

        $this->assertCount(1, $statements);
        $this->assertSame('create index raw_index on users ( (function(column)) )', $statements[0]);
    }

    public function test_adding_foreign_key()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->foreign('foo_id')->references('id')->on('orders');
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('alter table users add constraint users_foo_id_foreign foreign key ( foo_id ) references orders ( id )', $statements[0]);

        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->foreign('foo_id')->references('id')->on('orders')->cascadeOnDelete();
        $statements = $OracleBlueprint->toSql();

        $this->assertCount(1, $statements);
        $this->assertSame('alter table users add constraint users_foo_id_foreign foreign key ( foo_id ) references orders ( id ) on delete cascade', $statements[0]);

        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->foreign('foo_id')->references('id')->on('orders')->cascadeOnUpdate();
        $statements = $OracleBlueprint->toSql();

        $this->assertCount(1, $statements);
        $this->assertSame('alter table users add constraint users_foo_id_foreign foreign key ( foo_id ) references orders ( id ) on update cascade', $statements[0]);
    }

    public function test_adding_incrementing_id()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->increments('id');
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('alter table users add ( id number(10,0) generated by default on null as identity, constraint users_id_primary primary key ( id ))', $statements[0]);
    }

    public function test_adding_small_incrementing_id()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->smallIncrements('id');
        $statements = $OracleBlueprint->toSql();

        $this->assertCount(1, $statements);
        $this->assertSame('alter table users add ( id number(5,0) generated by default on null as identity, constraint users_id_primary primary key ( id ))', $statements[0]);
    }

    public function test_adding_id()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->id();
        $statements = $OracleBlueprint->toSql();

        $this->assertCount(1, $statements);
        $this->assertSame('alter table users add ( id number(10,0) generated by default on null as identity, constraint users_id_primary primary key ( id ))', $statements[0]);

        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->id('foo');
        $statements = $OracleBlueprint->toSql();

        $this->assertCount(1, $statements);
        $this->assertSame('alter table users add ( foo number(10,0) generated by default on null as identity, constraint users_foo_primary primary key ( foo ))', $statements[0]);
    }

    public function test_adding_foreign_id()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $foreignId = $OracleBlueprint->foreignId('foo');
        $OracleBlueprint->foreignId('company_id')->constrained();
        $OracleBlueprint->foreignId('laravel_idea_id')->constrained();
        $OracleBlueprint->foreignId('team_id')->references('id')->on('teams');
        $OracleBlueprint->foreignId('team_column_id')->constrained('teams');

        $statements = $OracleBlueprint->toSql();

        $this->assertInstanceOf(ForeignIdColumnDefinition::class, $foreignId);
        $this->assertCount(9, $statements);
        $this->assertSame([
            'alter table users add ( foo number(19,0) not null )',
            'alter table users add ( company_id number(19,0) not null )',
            'alter table users add constraint users_company_id_foreign foreign key ( company_id ) references companies ( id )',
            'alter table users add ( laravel_idea_id number(19,0) not null )',
            'alter table users add constraint users_laravel_idea_id_foreign foreign key ( laravel_idea_id ) references laravel_ideas ( id )',
            'alter table users add ( team_id number(19,0) not null )',
            'alter table users add constraint users_team_id_foreign foreign key ( team_id ) references teams ( id )',
            'alter table users add ( team_column_id number(19,0) not null )',
            'alter table users add constraint users_team_column_id_foreign foreign key ( team_column_id ) references teams ( id )',
        ], $statements);
    }

    public function test_adding_big_incrementing_id()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->bigIncrements('id');
        $statements = $OracleBlueprint->toSql();

        $this->assertCount(1, $statements);
        $this->assertSame('alter table users add ( id number(19,0) generated by default on null as identity, constraint users_id_primary primary key ( id ))', $statements[0]);
    }

    public function test_adding_string()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->string('foo');
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('alter table users add ( foo varchar2(255) not null )', $statements[0]);

        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->string('foo', 100);
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('alter table users add ( foo varchar2(100) not null )', $statements[0]);

        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->string('foo', 100)->nullable()->default('bar');
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('alter table users add ( foo varchar2(100) default \'bar\' null )', $statements[0]);

        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->string('foo', 100)->nullable()->default(new Raw('CURRENT TIMESTAMP'));
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('alter table users add ( foo varchar2(100) default CURRENT TIMESTAMP null )', $statements[0]);
    }

    public function test_adding_long_text()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->longText('foo');
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('alter table users add ( foo clob not null )', $statements[0]);
    }

    public function test_adding_medium_text()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->mediumText('foo');
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('alter table users add ( foo clob not null )', $statements[0]);
    }

    public function test_adding_text()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->text('foo');
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('alter table users add ( foo varchar2(4000) not null )', $statements[0]);
    }

    public function test_adding_big_integer()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->bigInteger('foo');
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('alter table users add ( foo number(19,0) not null )', $statements[0]);

        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->bigInteger('foo', true);
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('alter table users add ( foo number(19,0) not null, constraint users_foo_primary primary key ( foo ))', $statements[0]);
    }

    public function test_adding_integer()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->integer('foo');
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('alter table users add ( foo number(10,0) not null )', $statements[0]);

        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->integer('foo', true);
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('alter table users add ( foo number(10,0) not null, constraint users_foo_primary primary key ( foo ))', $statements[0]);
    }

    public function test_adding_increments_with_starting_values()
    {
        // calling ->startingValue() should have no effect on the generated sql because it hasn't been implemented

        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->id()->startingValue(1000);
        $statements = $OracleBlueprint->toSql();

        $this->assertCount(1, $statements);
        $this->assertSame('alter table users add ( id number(10,0) generated by default on null as identity, constraint users_id_primary primary key ( id ))', $statements[0]);
    }

    public function test_adding_medium_integer()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->mediumInteger('foo');
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('alter table users add ( foo number(7,0) not null )', $statements[0]);
    }

    public function test_adding_small_integer()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->smallInteger('foo');
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('alter table users add ( foo number(5,0) not null )', $statements[0]);
    }

    public function test_adding_tiny_integer()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->tinyInteger('foo');
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('alter table users add ( foo number(3,0) not null )', $statements[0]);
    }

    public function test_adding_float()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->float('foo', 5);
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('alter table users add ( foo float(5) not null )', $statements[0]);

        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->float('foo');
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('alter table users add ( foo float(126) not null )', $statements[0]);

        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->float('foo', null);
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('alter table users add ( foo float(126) not null )', $statements[0]);
    }

    public function test_adding_double()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->double('foo');
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('alter table users add ( foo float(126) not null )', $statements[0]);
    }

    public function test_adding_decimal()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->decimal('foo', 5, 2);
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('alter table users add ( foo number(5, 2) not null )', $statements[0]);
    }

    public function test_adding_boolean()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->boolean('foo');
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('alter table users add ( foo char(1) not null )', $statements[0]);
    }

    public function test_adding_enum()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->enum('foo', ['bar', 'baz']);
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('alter table users add ( foo varchar2(255) check(foo in (\'bar\', \'baz\')) not null )', $statements[0]);
    }

    public function test_adding_date()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->date('foo');
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('alter table users add ( foo date not null )', $statements[0]);
    }

    public function test_adding_date_time()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->dateTime('foo');
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('alter table users add ( foo date not null )', $statements[0]);
    }

    public function test_adding_time()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->time('foo');
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('alter table users add ( foo date not null )', $statements[0]);
    }

    public function test_adding_time_stamp()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->timestamp('foo');
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('alter table users add ( foo timestamp not null )', $statements[0]);
    }

    public function test_adding_timestamp_with_default()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->timestamp('created_at')->default(new Raw('CURRENT_TIMESTAMP'));
        $statements = $OracleBlueprint->toSql();
        $this->assertCount(1, $statements);
        $this->assertSame('alter table users add ( created_at timestamp default CURRENT_TIMESTAMP not null )', $statements[0]);
    }

    public function test_adding_time_stamps()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->timestamps();
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(2, count($statements));
        $this->assertSame([
            'alter table users add ( created_at timestamp null )',
            'alter table users add ( updated_at timestamp null )',
        ], $statements);
    }

    public function test_adding_binary()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->binary('foo');
        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('alter table users add ( foo blob not null )', $statements[0]);
    }

    public function test_adding_comment()
    {
        // calling ->comment() on a column should have no effect on the generated sql because it hasn't been implemented

        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->string('foo')->comment("Escape ' when using words like it's");
        $statements = $OracleBlueprint->toSql();

        $this->assertCount(1, $statements);
        $this->assertSame('alter table users add ( foo varchar2(255) not null )', $statements[0]);
    }

    public function test_basic_select_using_quotes()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(quoting: true), 'users');
        $OracleBlueprint->create();
        $OracleBlueprint->increments('id');
        $OracleBlueprint->string('email');

        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('create table "users" ( "id" number(10,0) generated by default on null as identity, "email" varchar2(255) not null, constraint users_id_primary primary key ( "id" ))', $statements[0]);
    }

    public function test_basic_select_not_using_quotes()
    {
        $OracleBlueprint = new OracleBlueprint($this->getConnection(), 'users');
        $OracleBlueprint->create();
        $OracleBlueprint->increments('id');
        $OracleBlueprint->string('email');

        $statements = $OracleBlueprint->toSql();

        $this->assertEquals(1, count($statements));
        $this->assertEquals('create table users ( id number(10,0) generated by default on null as identity, email varchar2(255) not null, constraint users_id_primary primary key ( id ))', $statements[0]);
    }

    public function test_grammars_are_macroable()
    {
        // compileReplace macro.
        $this->getGrammar()::macro('compileReplace', function () {
            return true;
        });

        $c = $this->getGrammar()::compileReplace();

        $this->assertTrue($c);
    }

    protected function getConnection(
        ?OracleGrammar $grammar = null,
        ?OracleBuilder $builder = null,
        string $prefix = '',
        bool $quoting = false
    ) {
        $connection = m::mock(OracleConnection::class)
            ->shouldReceive('getTablePrefix')->andReturn($prefix)
            ->shouldReceive('getConfig')->with('prefix_indexes')->andReturn(null)
            ->shouldReceive('getConfig')->with('quoting')->andReturn($quoting)
            ->getMock();

        $grammar ??= $this->getGrammar($connection);
        $builder ??= $this->getBuilder();

        return $connection
            ->shouldReceive('getSchemaGrammar')->andReturn($grammar)
            ->shouldReceive('getSchemaBuilder')->andReturn($builder)
            ->getMock();
    }

    public function getGrammar(?OracleConnection $connection = null)
    {
        return new OracleGrammar($connection ?? $this->getConnection());
    }

    public function getBuilder()
    {
        return mock(OracleBuilder::class);
    }
}
